spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: '12341234'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    basic:
      enabled: false
jwt:
  secret: mySuperSecretKey1234567890123456
  expiration: 86400000