spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mariadb://database-p2.cx00oo0eeajx.ap-northeast-2.rds.amazonaws.com:3306/shopping?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

logging:
  config: classpath:logback-spring-prod.xml  # 프로덕션용 로깅 설정

springdoc:
  api-docs:
    path: /v3/api-docs  # API 문서 경로
  swagger-ui:
    path: /swagger-ui/index.html
