spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mariadb://database-1.c5weow084e6r.ap-northeast-2.rds.amazonaws.com:3306/shopping?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  security:
    basic:
      enabled: false

springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui/index.html

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

logging:
  config: classpath:logback-spring-prod.xml
